version: '3'
services:
  dev:
    image: golang:1.15
    environment:
      GO111MODULE: 'on'
      DYNAMODB_ENDPOINT: http://dynamodb.local:8000
      REDIS_ADDRESS: redis.local:6379
    links:
      - dynamodb:dynamodb.local
      - redis:redis.local
    volumes:
      - .:/go/src/github.com/ccbrown/keyvaluestore
    working_dir: /go/src/github.com/ccbrown/keyvaluestore
  redis:
    image: redis
  dynamodb:
    image: amazon/dynamodb-local
